language: python

services:
  - rabbitmq

# Conflicts with pypy install :/
sudo: false

# addons:
#  apt:
#    sources:
#    - pypy
# addons:
#  apt:
#    packages:
#    - pypy

env:
    - TOX_ENV=py27-twlatest
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=py27-tw154
    - TOX_ENV=py27-tw153
    - TOX_ENV=py27-tw150
    - TOX_ENV=py27-tw140
    - TOX_ENV=py33-twtrunk
    - TOX_ENV=py34-twtrunk
    # - TOX_ENV=pypy-twtrunk
    - TOX_ENV=pyflakes
    - TOX_ENV=manifest

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py33-twtrunk
    - env: TOX_ENV=py34-twtrunk

# before_install:
#   - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 68854915"
#   - "echo 'deb http://ppa.launchpad.net/pypy/ppa/ubuntu '$(lsb_release -sc)' main' | sudo tee /etc/apt/sources.list.d/pypy.list"
#   - "sudo apt-get update"
#   - "sudo apt-get install pypy"
#   - "pypy --version"

install:
  - pip install tox coveralls

before_script:
  - "until nc -z localhost 5672; do echo Waiting for Rabbit; sleep 1; done"

script:
  - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    email: false
